[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Android-Development Wiki"
authors = [{name = "Phillip Unzen", email = "development@phillipunzen.de"}]
dynamic = ["version", "description"]
